"""Genera los iconos pixel de 16x16 del menú de FreedomClient.

Uso: python3 tools/make_icons.py   (requiere Pillow)
Cada icono se define como 16 filas de 16 caracteres; cada carácter es un color de la paleta.
"""
from pathlib import Path
from PIL import Image

OUT = Path(__file__).resolve().parent.parent / "src/main/resources/assets/freedomclient/textures/icon"

PALETTE = {
    ".": None,
    "k": (0x1A, 0x05, 0x08),  # contorno
    "g": (0xF2, 0xC9, 0x4C),  # dorado (halo)
    "G": (0xC9, 0x8F, 0x1E),  # dorado oscuro
    "r": (0xD7, 0x26, 0x3D),  # rojo (pelo)
    "R": (0x8E, 0x14, 0x26),  # rojo oscuro
    "o": (0xFF, 0x8C, 0x42),  # naranja atardecer
    "s": (0x5D, 0xAD, 0xE2),  # azul cielo
    "S": (0x2E, 0x6E, 0xA8),  # azul oscuro
    "w": (0xF5, 0xF1, 0xE8),  # blanco (alas)
    "W": (0xB8, 0xB0, 0xA4),  # gris claro
}

ICONS = {
    "toggle_sprint": [
        "................",
        ".........kkk....",
        "........kwwwk...",
        "........kwwwk...",
        ".........kkk....",
        "......kkkrrk....",
        ".....krrrrrrk...",
        "....krkrrrkrrk..",
        "...kk.krrrk.kk..",
        "......kSSSk.....",
        ".....kSSkSSk....",
        "....kSSk.kSSk...",
        "..kkSSk...kSk...",
        "..kSSk....kSSk..",
        "..kkk......kkk..",
        "................",
    ],
    "watermark": [
        "................",
        "....kkkkkkkk....",
        "...kggggggggk...",
        "....kkkkkkkk....",
        "................",
        ".kkkkkk..kkkkk..",
        ".krrrrk.krrrrrk.",
        ".krkkkk.krkkkk..",
        ".krrrk..krk.....",
        ".krkkk..krk.....",
        ".krk....krkkkk..",
        ".krk.....krrrrk.",
        ".kkk......kkkk..",
        "................",
        "................",
        "................",
    ],
    "fps": [
        "................",
        ".kkkkkkkkkkkkkk.",
        ".kSSSSSSSSSSSSk.",
        ".kSsssssssssgSk.",
        ".kSssssssssggSk.",
        ".kSsssssgsggsSk.",
        ".kSsssgggggssSk.",
        ".kSsgggsgsssSSk.",
        ".kSggsssssssSSk.",
        ".kSSSSSSSSSSSSk.",
        ".kkkkkkkkkkkkkk.",
        "......kWWk......",
        "......kWWk......",
        "....kkkkkkkk....",
        "....kWWWWWWk....",
        "....kkkkkkkk....",
    ],
    "ping": [
        "................",
        "................",
        "............kkk.",
        "............kgk.",
        "............kgk.",
        "........kkk.kgk.",
        "........kgk.kgk.",
        "........kgk.kgk.",
        "....kkk.kgk.kgk.",
        "....kgk.kgk.kgk.",
        "....kgk.kgk.kgk.",
        "kkk.kgk.kgk.kgk.",
        "krk.kgk.kgk.kgk.",
        "krk.kgk.kgk.kgk.",
        "kkk.kkk.kkk.kkk.",
        "................",
    ],
    "coordinates": [
        "................",
        ".....kkkkkk.....",
        "...kkwwwwwwkk...",
        "..kwwwwrrwwwwk..",
        "..kwwwwrrwwwwk..",
        ".kwwwwrrrrwwwwk.",
        ".kwwwwrrrrwwwwk.",
        ".kwwwwwkkwwwwwk.",
        ".kwwwwwkkwwwwwk.",
        ".kwwwwSSSSwwwwk.",
        ".kwwwwSSSSwwwwk.",
        "..kwwwwSSwwwwk..",
        "..kwwwwSSwwwwk..",
        "...kkwwwwwwkk...",
        ".....kkkkkk.....",
        "................",
    ],
    "keystrokes": [
        "................",
        "................",
        "................",
        ".....kkkkkk.....",
        ".....kggggk.....",
        ".....kgkkgk.....",
        ".....kgkkgk.....",
        ".....kGGGGk.....",
        ".....kkkkkk.....",
        "kkkkkkkkkkkkkkkk",
        "kwwwwkwwwwkwwwwk",
        "kwkkwkwkkwkwkkwk",
        "kwkkwkwkkwkwkkwk",
        "kWWWWkWWWWkWWWWk",
        "kkkkkkkkkkkkkkkk",
        "................",
    ],
    "armor_hud": [
        "................",
        "..kkkk....kkkk..",
        ".kssssk..kssssk.",
        ".kssssskkssssssk",
        ".kSssssssssssSk.",
        "..kkSsssssssSkk.",
        "....kssssssk....",
        "....kssgsssk....",
        "....kssssssk....",
        "....kSssssSk....",
        "....kssssssk....",
        "....kSssssSk....",
        "....kssssssk....",
        "....kSSSSSSk....",
        "....kkkkkkkk....",
        "................",
    ],
    "module_list": [
        "................",
        ".kkk.kkkkkkkkkk.",
        ".kgk.kwwwwwwwwk.",
        ".kkk.kkkkkkkkkk.",
        "................",
        ".kkk.kkkkkkkk...",
        ".kgk.kwwwwwwk...",
        ".kkk.kkkkkkkk...",
        "................",
        ".kkk.kkkkkkkkkk.",
        ".krk.kwwwwwwwwk.",
        ".kkk.kkkkkkkkkk.",
        "................",
        ".kkk.kkkkkk.....",
        ".ksk.kwwwwk.....",
        ".kkk.kkkkkk.....",
    ],
    "fullbright": [
        "................",
        ".......gg.......",
        "..g....gg....g..",
        "...g........g...",
        "......kkkk......",
        ".....kggggk.....",
        "....kggoogGk....",
        "gg..kgoooggk..gg",
        "gg..kggooggk..gg",
        "....kGgggGGk....",
        ".....kGGGGk.....",
        "......kkkk......",
        "...g........g...",
        "..g....gg....g..",
        ".......gg.......",
        "................",
    ],
    "zoom": [
        "................",
        "....kkkkk.......",
        "...kssssskk.....",
        "..kswwssssSk....",
        ".kswwssssssSk...",
        ".kswssssssssk...",
        ".ksssssssssSk...",
        ".ksssssssssSk...",
        ".kSssssssSSSk...",
        "..kSSssSSSSk....",
        "...kkSSSSkkGk...",
        ".....kkkkkGggk..",
        "..........kGggk.",
        "...........kGggk",
        "............kGgk",
        ".............kk.",
    ],
    "fps_optimizer": [
        "................",
        ".........kkkk...",
        "........kggGk...",
        ".......kggGk....",
        "......kggGk.....",
        ".....kggGk......",
        "....kggggkkkk...",
        "...kggggggggk...",
        "...kkkkkggGk....",
        ".......kggk.....",
        "......kggk......",
        ".....kgGk.......",
        "....kgGk........",
        "...kgk..........",
        "...kk...........",
        "................",
    ],
    "wings": [
        "................",
        "kk............kk",
        "kwk..........kwk",
        "kwwk........kwwk",
        "kwwwk......kwwwk",
        "kwwWwk....kwWwwk",
        ".kwwWwk..kwWwwk.",
        ".kwwwWwkkwWwwwk.",
        "..kwwwWkkWwwwk..",
        "..kwwwwkkwwwwk..",
        "...kwWwkkwWwk...",
        "...kwwk..kwwk...",
        "....kWk..kWk....",
        "....kk....kk....",
        "................",
        "................",
    ],
    "halo": [
        "................",
        "................",
        "................",
        "....kkkkkkkk....",
        "..kkggggggggkk..",
        ".kggGGkkkkGGggk.",
        ".kgGk......kGgk.",
        ".kggGkkkkkkGggk.",
        "..kkggggggggkk..",
        "....kkkkkkkk....",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
    ],
    "cape": [
        "................",
        "...kkkkkkkkkk...",
        "..kgRRRRRRRRgk..",
        "..krrrrrrrrrrk..",
        "..krrrrrrrrrrk..",
        "..krrrgrrgrrrk..",
        "..krrrrggrrrrk..",
        ".krrrrrggrrrrrk.",
        ".krrrrgrrgrrrrk.",
        ".krrrrrrrrrrrrk.",
        ".kRrrrrrrrrrrRk.",
        ".kRRrrrrrrrrRRk.",
        "kRRRRrrrrrrRRRRk",
        "kRkRRRkRRkRRRkRk",
        "kk.kkk.kk.kkk.kk",
        "................",
    ],
    "clock": [
        "................",
        ".....kkkkkk.....",
        "...kkggggggkk...",
        "..kgggwwwwgggk..",
        "..kggwwwkwwggk..",
        ".kggwwwwkwwwggk.",
        ".kgwwwwwkwwwwgk.",
        ".kgwwwwwkkkkwgk.",
        ".kgwwwwwwwwwwgk.",
        ".kggwwwwwwwwggk.",
        "..kggwwwwwwggk..",
        "..kgggwwwwgggk..",
        "...kkGGGGGGkk...",
        ".....kkkkkk.....",
        "................",
        "................",
    ],
    "cps": [
        "................",
        "....kkkkkkkk....",
        "...kwwwwkssssk..",
        "..kwwwwwkssssk..",
        "..kwwwwwkssssk..",
        "..kwwwwwkssssk..",
        "..kkkkkkkkkkkk..",
        "..kWWWWWWWWWWk..",
        "..kwwwwwwwwwwk..",
        "..kwwwwwwwwwwk..",
        "..kwwwwwwwwwwk..",
        "..kWwwwwwwwwWk..",
        "...kWWwwwwWWk...",
        "....kkkkkkkk....",
        "................",
        "................",
    ],
    "combo": [
        "................",
        "............kk..",
        "...........kwk..",
        "..........kwk...",
        ".........kwk....",
        "........kwk.....",
        "..kk...kwk......",
        "..kWk.kwk.......",
        "...kWkwk........",
        "....kGk.........",
        "...kGkGk........",
        "..kGk.kGk..rrr..",
        ".kGk...kk.r...r.",
        ".kk.........rr..",
        "...........r....",
        "...........rrrr.",
    ],
    "reach": [
        "................",
        "................",
        "................",
        "..k..........k..",
        ".kk..........kk.",
        "kgkkkkkkkkkkkkgk",
        "kggggggggggggggk",
        "kgkkkkkkkkkkkkgk",
        ".kk..........kk.",
        "..k..........k..",
        "................",
        "...kk......kk...",
        "...ks......sk...",
        "...kk......kk...",
        "................",
        "................",
    ],
    "armor_alert": [
        "................",
        ".......kk.......",
        "......krrk......",
        "......krrk......",
        ".....krrrrk.....",
        ".....krwwrk.....",
        "....krrwwrrk....",
        "....krrwwrrk....",
        "...krrrwwrrrk...",
        "...krrrwwrrrk...",
        "..krrrrrrrrrrk..",
        "..krrrrwwrrrrk..",
        ".krrrrrwwrrrrrk.",
        ".kRRRRRRRRRRRRk.",
        ".kkkkkkkkkkkkkk.",
        "................",
    ],
    "inventory_hud": [
        "................",
        "kkkkkkkkkkkkkkkk",
        "kWWWWkWWWWkWWWWk",
        "kWrrWkWWWWkWssWk",
        "kWrrWkWWWWkWssWk",
        "kWWWWkWWWWkWWWWk",
        "kkkkkkkkkkkkkkkk",
        "kWWWWkWWWWkWWWWk",
        "kWWWWkWggWkWWWWk",
        "kWWWWkWggWkWWWWk",
        "kWWWWkWWWWkWWWWk",
        "kkkkkkkkkkkkkkkk",
        "kWWWWkWWWWkWWWWk",
        "kWWWWkWWWWkWWWWk",
        "kkkkkkkkkkkkkkkk",
        "................",
    ],
    "potion_effects": [
        "................",
        "......kkkk......",
        "......kWWk......",
        ".......kk.......",
        "......kwwk......",
        ".....kwwwwk.....",
        "....kwwwwwwk....",
        "...kwrrrrrrwk...",
        "..kwrrrrrrrrwk..",
        "..kwrrwrrrrrwk..",
        "..kwrrrrrrrrwk..",
        "..kwRrrrrrrRwk..",
        "...kwRRRRRRwk...",
        "....kkkkkkkk....",
        "................",
        "................",
    ],
    "item_counter": [
        "................",
        "..kkkk..........",
        ".kggggk.........",
        ".kgwggk.........",
        ".kggggk.........",
        "..kkkk..........",
        "..........kkkk..",
        ".........kssssk.",
        ".........ksSssk.",
        ".........kssssk.",
        "..........kkkk..",
        "................",
        "..kkkk.kk.kkk...",
        "..kwwk.kk..kk...",
        "..kkkk.kk.kkk...",
        "................",
    ],
    "appleskin": [
        "................",
        ".......kk.......",
        "......kGk.......",
        "......kk.kkk....",
        "...kkkkkkssk....",
        "..krrrrrkkkk....",
        ".krrwrrrrrrrk...",
        ".krwrrrrrrrrk...",
        ".krrrrrrrrrrk...",
        ".krrrrrrrrrrk...",
        ".kRrrrrrrrrRk...",
        "..kRrrrrrrRk....",
        "..kRRRkRRRRk....",
        "...kkk.kkkk.....",
        "................",
        "................",
    ],
    "gear": [
        "................",
        "......kkkk......",
        "..kk..kWWk..kk..",
        "..kWkkkwwkkkWk..",
        "...kwwwwwwwwk...",
        "...kwwWkkWwwk...",
        ".kkkwWk..kWwkkk.",
        ".kWwwk....kwwWk.",
        ".kWwwk....kwwWk.",
        ".kkkwWk..kWwkkk.",
        "...kwwWkkWwwk...",
        "...kwwwwwwwwk...",
        "..kWkkkwwkkkWk..",
        "..kk..kWWk..kk..",
        "......kkkk......",
        "................",
    ],
}


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    for name, rows in ICONS.items():
        assert len(rows) == 16 and all(len(row) == 16 for row in rows), name
        image = Image.new("RGBA", (16, 16), (0, 0, 0, 0))
        for y, row in enumerate(rows):
            for x, char in enumerate(row):
                color = PALETTE[char]
                if color is not None:
                    image.putpixel((x, y), color + (255,))
        image.save(OUT / f"{name}.png")
    print(f"{len(ICONS)} icons written to {OUT}")


if __name__ == "__main__":
    main()
